qwt6: Install either libqwt-qt5-dev or libqwt-dev
In Debian testing the libqwt-dev package has been removed so replace &&
with ||. Fix the rpms as well.

Update the source URL to version 6.1.4 to fix the following errors:

qwt_transform.h:110:5: error: ‘QT_STATIC_CONST’ does not name a type
110 | QT_STATIC_CONST double LogMin;
| ^~~~~~~~~~~~~~~
qwt_transform.h:111:5: error: ‘QT_STATIC_CONST’ does not name a type
111 | QT_STATIC_CONST double LogMax;
| ^~~~~~~~~~~~~~~